name: Publish Home Assistant

on:
  repository_dispatch:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  lint_repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Hadolint
        uses: brpaz/hadolint-action@v1.1.0
        continue-on-error: true

  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set vars
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and publish
        id: vars
        run: |
          ./build.sh push

      # - name: Push to Docker Hub
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     build-args: |
      #       HASS_VERSION=${{ steps.vars.outputs.short_ref }}
      #       ALPINE_VERSION=3.12
      #     tags: |
      #       failfr8er/home-assistant:${{ steps.vars.outputs.short_ref }}
      #       failfr8er/home-assistant:latest
      #     platforms: linux/amd64,linux/arm64,linux/arm/v7
      #     cache-from: type=local,src=/tmp/.buildx-cache
      #     cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Run Dive
        uses: yuichielectric/dive-action@0.0.4
        continue-on-error: true
        with:
          image: "failfr8er/home-assistant:${{ steps.vars.outputs.short_ref }}"
          config-file: ${{ github.workspace }}/.dive-ci.yml

      - name: Container image scan
        uses: Azure/container-scan@v0
        continue-on-error: true
        with:
          image-name: "failfr8er/home-assistant:${{ steps.vars.outputs.short_ref }}"

      - name: Rollback Release
        if: failure()
        uses: author/action-rollback@stable
        with:
          tag: ${{ steps.vars.outputs.short_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
