name: Publish Home Assistant

on:
  repository_dispatch:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  lint_repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Hadolint
        uses: brpaz/hadolint-action@v1.1.0
        continue-on-error: true

  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and publish
        id: build_and_push
        run: |
          set -x
          ALPINE_VERSION=3.12
          IMAGE_NAME=failfr8er/home-assistant
          HASS_RAW=$(curl -H "Accept: application/vnd.github.v3+json" -s https://api.github.com/repos/home-assistant/core/releases/latest)
          HASS_VERSION=$(echo "${HASS_RAW}" | jq -r '.tag_name')

          echo "Building and pushing Home Assistant ${HASS_VERSION}"
          echo "::set-output name=HASS_VERSION::${HASS_VERSION}"

          docker buildx build \
            --file Dockerfile \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache \
            --tag ${IMAGE_NAME}:${HASS_VERSION} \
            --tag ${IMAGE_NAME}:latest \
            --push \
            --build-arg ALPINE_VERSION=${ALPINE_VERSION} \
            --build-arg HASS_VERSION=${HASS_VERSION} \
            --platform=linux/amd64,linux/arm64 \
            --progress plain \
            .

      - name: Run Dive
        uses: yuichielectric/dive-action@0.0.4
        continue-on-error: true
        with:
          image: "failfr8er/home-assistant:${{ steps.build_and_push.outputs.HASS_VERSION }}"
          config-file: ${{ github.workspace }}/.dive-ci.yml

      - name: Container image scan
        uses: Azure/container-scan@v0
        continue-on-error: true
        with:
          image-name: "failfr8er/home-assistant:${{ steps.build_and_push.outputs.HASS_VERSION }}"

      - name: Rollback Release
        if: failure()
        uses: author/action-rollback@stable
        with:
          tag: ${{ steps.vars.outputs.short_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
